name: Build and Push Docker Image with Terraform + Terragrunt + awscli

on:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
      - ".github/workflows/build_docker_image.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build & Push Docker image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.repository }}:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ github.repository }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=https://github.com/ ${{ github.repository }}
            org.opencontainers.image.version=latest